const stakePool = artifacts.require("stakePool");
const fnxProxy = artifacts.require("fnxProxy");
const FPTCoin = artifacts.require("FPTCoin");
let eth = "0x0000000000000000000000000000000000000000";
contract('stakePool', function (accounts){
    it('stakePool normal tests', async function (){
        let fptCoin = await FPTCoin.new();
        let stakepool = await stakePool.new();
        await stakepool.setPoolInfo(fptCoin.address,eth,50);
        let addr = await stakepool.getFPTCoinAddress();
        console.log("getFPTCoinAddress : ",addr);
        addr = await stakepool.poolToken();
        console.log("poolToken : ",addr);
        let interest = await stakepool.interestRate();
        console.log("interestRate : ",interest.toNumber());
        interest = await stakepool.poolBalance();
        console.log("poolBalance : ",interest.toNumber());
        interest = await stakepool.FPTTotalSuply();
        console.log("FPTTotalSuply : ",interest.toNumber());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toNumber());
    });
    it('stakePool stake tests', async function (){
        let fptCoin = await FPTCoin.new();
        await fptCoin.setTimeLimitation(0);
        let stakepool = await stakePool.new();
        fptCoin.setManager(stakepool.address);
        await stakepool.setPoolInfo(fptCoin.address,eth,50);
        let addr = await stakepool.getFPTCoinAddress();
        console.log("getFPTCoinAddress : ",addr);
        addr = await stakepool.poolToken();
        console.log("poolToken : ",addr);
        let interest = await stakepool.interestRate();
        console.log("interestRate : ",interest.toNumber());
        await stakepool.stake("1000000000000000000",{value:"1000000000000000000"});
        for(var i=0;i<50;i++){
            await fptCoin.setTimeLimitation(0);
        }
        interest = await web3.eth.getBalance(accounts[0]);
        console.log("poolBalance : ",interest.toString());
        interest = await stakepool.poolBalance();
        console.log("poolBalance : ",interest.toString());
        interest = await stakepool.FPTTotalSuply();
        console.log("FPTTotalSuply : ",interest.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
        await stakepool.unstake("1000000000000000000");
        interest = await web3.eth.getBalance(accounts[0]);
        console.log("poolBalance : ",interest.toString());
        interest = await stakepool.poolBalance();
        console.log("poolBalance : ",interest.toString());
        interest = await stakepool.FPTTotalSuply();
        console.log("FPTTotalSuply : ",interest.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
    });
    it('stakePool borrow tests', async function (){
        let fptCoin = await FPTCoin.new();
        await fptCoin.setTimeLimitation(0);
        let stakepool = await stakePool.new();
        fptCoin.setManager(stakepool.address);
        await stakepool.setPoolInfo(fptCoin.address,eth,5e5);
        let addr = await stakepool.getFPTCoinAddress();
        console.log("getFPTCoinAddress : ",addr);
        addr = await stakepool.poolToken();
        console.log("poolToken : ",addr);
        let interest = await stakepool.interestRate();
        console.log("interestRate : ",interest.toNumber());
        await stakepool.stake("1000000000000000000",{value:"1000000000000000000"});
        await stakepool.borrow("1000000000000000000");
        let balance = await web3.eth.getBalance(accounts[0]);
        console.log("balance : ",balance.toString());
        balance = await web3.eth.getBalance(stakepool.address);
        console.log("balance : ",balance.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
        await stakepool.stake("1000000000000000000",{value:"1000000000000000000"});
        await stakepool.borrowAndInterest("1000000000000000000");
        balance = await web3.eth.getBalance(accounts[0]);
        console.log("balance : ",balance.toString());
        balance = await web3.eth.getBalance(stakepool.address);
        console.log("balance : ",balance.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
        await stakepool.repayAndInterest("1000000000000000000",{value:"1000000000000000000"}); 
        balance = await web3.eth.getBalance(accounts[0]);
        console.log("balance : ",balance.toString());
        balance = await web3.eth.getBalance(stakepool.address);
        console.log("balance : ",balance.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
        await stakepool.repay("1000000000000000000",{value:"1000000000000000000"}); 
        balance = await web3.eth.getBalance(accounts[0]);
        console.log("balance : ",balance.toString());
        balance = await web3.eth.getBalance(stakepool.address);
        console.log("balance : ",balance.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
    });
    it('IStakePool borrow tests', async function (){
        let fptCoin = await FPTCoin.new();
        await fptCoin.setTimeLimitation(0);
        let stakeimple = await stakePool.new();
        let stakepool = await fnxProxy.new(stakeimple.address,1);
        stakepool = await stakePool.at(stakepool.address);
        fptCoin.setManager(stakepool.address);
        await stakepool.setPoolInfo(fptCoin.address,eth,5e5);
        let addr = await stakepool.getFPTCoinAddress();
        console.log("getFPTCoinAddress : ",addr);
        addr = await stakepool.poolToken();
        console.log("poolToken : ",addr);
        let interest = await stakepool.interestRate();
        console.log("interestRate : ",interest.toNumber());
        await stakepool.stake("1000000000000000000",{value:"1000000000000000000"});
        await stakepool.borrow("1000000000000000000");
        let balance = await web3.eth.getBalance(accounts[0]);
        console.log("balance : ",balance.toString());
        balance = await web3.eth.getBalance(stakepool.address);
        console.log("balance : ",balance.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
        await stakepool.stake("1000000000000000000",{value:"1000000000000000000"});
        await stakepool.borrowAndInterest("1000000000000000000");
        balance = await web3.eth.getBalance(accounts[0]);
        console.log("balance : ",balance.toString());
        balance = await web3.eth.getBalance(stakepool.address);
        console.log("balance : ",balance.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
        await stakepool.repayAndInterest("1000000000000000000",{value:"1000000000000000000"}); 
        balance = await web3.eth.getBalance(accounts[0]);
        console.log("balance : ",balance.toString());
        balance = await web3.eth.getBalance(stakepool.address);
        console.log("balance : ",balance.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
        await stakepool.repay("1000000000000000000",{value:"1000000000000000000"}); 
        balance = await web3.eth.getBalance(accounts[0]);
        console.log("balance : ",balance.toString());
        balance = await web3.eth.getBalance(stakepool.address);
        console.log("balance : ",balance.toString());
        interest = await stakepool.tokenNetworth();
        console.log("tokenNetworth : ",interest.toString());
    });
});